### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by zwilias** [zwilias/elm-json#19]
The following travis config gets fairly close:

```yaml
addons:
  apt:
    packages:
      - musl-tools
      - gcc-arm-linux-gnueabihf

matrix:
  include:
    - name: RPI
      env: TARGET=armv7-unknown-linux-musleabihf CC_armv7_unknown_linux_musleabihf=arm-linux-gnueabihf-gcc CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER=arm-linux-gnueabihf-gcc
```
but ultimately still result in build failure, however, that's probably because of something I did: https://travis-ci.org/zwilias/elm-json/jobs/621652061
